[package]
name = "libzip-sys"
version = "0.1.0"
authors = ["Dicomserver Team"]
edition = "2021"
description = "Bindgen bindings to system libzip"
build = "build.rs"
links = "zip"

[dependencies]
libz-sys = { version = "1", default-features = false, features = ["zlib-ng"] }

[build-dependencies]
bindgen = "0.60"
cmake = "0.1"
mockall = "0.11.2"
