[package]
name = "libzip-sys"
version = "0.1.0"
authors = ["Dicomserver Team"]
edition = "2021"
description = "Bindgen bindings to system libzip"
build = "build.rs"
links = "zip"

[dependencies]
openssl-sys = { version = "0.9", optional = true }
libz-sys = { version = "1", optional = true, default-features = false }
tokio = { version = "1", features = ["full"] }
tracing = { version = "0.1" }

[build-dependencies]
bindgen = "0.60"
cmake = "0.1"
mockall = "0.11.2"

[features]
default = []
static = ["openssl-sys/vendored", "libz-sys/zlib-ng"]
