[target.x86_64-unknown-linux-gnu]
image = "ghcr.io/dougyau/cross/x86_64-unknown-linux-gnu:latest"
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get install --assume-yes libssl-dev:$CROSS_DEB_ARCH libgdcm-dev:$CROSS_DEB_ARCH libzip-dev:$CROSS_DEB_ARCH",
]
